### ISSUE TITLE
No fonts

### ISSUE THREAD

**Issue by POD-io** [nkchocoai/ComfyUI-TextOnSegs#1]
Clicking on font or trying to scroll left and right does not change from 'undefined'.

I have confirmed the normal 'CR Draw Text' node loads fonts that I place there however. What would cause this to not detect any fonts?
![image](https://github.com/nkchocoai/ComfyUI-TextOnSegs/assets/7347364/638e9622-ac4f-476c-b5e1-e0aa88c7fc9b)

**Comment by POD-io** [comment]
The only way I've been able to load a font is to convert the 'font' widget to an input, and then use the 'CR Select Font' node.

**Comment by nkchocoai** [comment]
> Clicking on font or trying to scroll left and right does not change from 'undefined'.

Are you referring to the "Draw Text" node on the right side of the attached image?

I think this node is for the extension "ComfyUI Essentials" and the font files should be placed in the extension's fonts directory.
https://github.com/cubiq/ComfyUI_essentials/

**Comment by POD-io** [comment]
> > Clicking on font or trying to scroll left and right does not change from 'undefined'.
> 
> Are you referring to the "Draw Text" node on the right side of the attached image?
> 
> I think this node is for the extension "ComfyUI Essentials" and the font files should be placed in the extension's fonts directory. https://github.com/cubiq/ComfyUI_essentials/

Yes indeed, that is the node. Thank you for that info! I will try and raise the issue there.
